-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 7.5
-- Fri Nov 24 11:26:06 2023

-- parameterized module component declaration
component boot_ram
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(11 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : boot_ram
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(11 downto 0)=>__, 
        Data(7 downto 0)=>__, Q(7 downto 0)=>__);
