-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.13.0.56.2
-- Module  Version: 7.5
-- Thu Feb 15 00:12:07 2024

-- parameterized module component declaration
component cart_ram
    port (Clock: in  std_logic; ClockEn: in  std_logic; 
        Reset: in  std_logic; WE: in  std_logic; 
        Address: in  std_logic_vector(10 downto 0); 
        Data: in  std_logic_vector(7 downto 0); 
        Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : cart_ram
    port map (Clock=>__, ClockEn=>__, Reset=>__, WE=>__, Address(10 downto 0)=>__, 
        Data(7 downto 0)=>__, Q(7 downto 0)=>__);
