-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 5.7
-- Fri Mar 31 15:12:18 2023

-- parameterized module component declaration
component pll
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, LOCK=>__);
